DROP TABLE IF EXISTS available_volunteers CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS timeslots CASCADE;
DROP TABLE IF EXISTS days CASCADE;

CREATE TABLE days (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE timeslots (
  id SERIAL PRIMARY KEY NOT NULL,
  time VARCHAR(255) NOT NULL,
  day_id INTEGER REFERENCES days(id) ON DELETE CASCADE
);

CREATE TABLE volunteers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  timeslots_id INTEGER REFERENCES timeslots(id) ON DELETE CASCADE,
  day_id INTEGER REFERENCES days(id) ON DELETE CASCADE,
  title VARCHAR(255),
  volunteers_id INTEGER[2],
  waitlist INTEGER[3]
);

CREATE TABLE available_volunteers (
  id SERIAL PRIMARY KEY NOT NULL,
  day_id INTEGER REFERENCES days(id) ON DELETE CASCADE,
  volunteers_id INTEGER REFERENCES volunteers(id) ON DELETE CASCADE
);
